apiVersion: v2
name: ts-server-boilerplate
description: A Helm chart for ts-server-boilerplate service
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: mclabels
    version: 1.0.1
    repository: oci://acrarolibotnonprod.azurecr.io/helm/infra
